[package]
authors = { workspace = true }
description = "gateway-tests contain integration tests for the gateway"
edition = { workspace = true }
license = { workspace = true }
name = "gateway-tests"
publish = false
version = { workspace = true }

# workaround: cargo-deny in Nix needs to see at least one
# artifact here
[[bin]]
name = "gateway-tests"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
devimint = { workspace = true }
fedimint-core = { workspace = true }
fedimint-gateway-common = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-testing-core = { workspace = true }
itertools = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
