[package]
name = "fedimint-meta-tests"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "fedimint-mint-tests contains integration tests for the meta module"
license = { workspace = true }
publish = false

# workaround: cargo-deny in Nix needs to see at least one
# artifact here
[[bin]]
name = "meta-module-tests"
path = "src/bin/meta-module-tests.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
devimint = { workspace = true }
fedimint-core = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
