[package]
authors = { workspace = true }
description = "IndexedDB database implementation for Fedimint WASM clients"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-indexeddb"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
name = "fedimint_indexeddb"
path = "src/lib.rs"

[target.'cfg(target_family = "wasm")'.dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
fedimint-core = { workspace = true }
futures = { workspace = true }
imbl = { workspace = true }
js-sys = { workspace = true }
rexie = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
