[package]
authors = { workspace = true }
description = "Contains common structs and logic between the gateway client and server"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-gateway-common"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[features]
tor = ["fedimint-api-client/tor"]

[lib]
name = "fedimint_gateway_common"
path = "src/lib.rs"

[dependencies]
bitcoin = { workspace = true }
clap = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-eventlog = { workspace = true }
fedimint-lnv2-common = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-wallet-client = { workspace = true }
lightning-invoice = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
