[package]
authors = { workspace = true }
description = "tpe is a helper cryptography library for threshold point encryption"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-tpe"
version = { workspace = true }

[features]
default = []
unstable = []

[lib]
name = "tpe"
path = "src/lib.rs"

[dependencies]
bitcoin_hashes = { workspace = true }
bls12_381 = { workspace = true }
fedimint-core = { workspace = true }
group = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
serde-big-array = { workspace = true }

[lints]
workspace = true
