[package]
authors = { workspace = true }
description = "Fedimint derivable secret implementation"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-derive-secret"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_derive_secret"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bitcoin_hashes = { workspace = true }
bls12_381 = { workspace = true }
fedimint-core = { workspace = true }
hkdf = { workspace = true }
ring = { workspace = true }

[lints]
workspace = true
