[package]
authors = { workspace = true }
description = "fedimint-dummy is a dummy example fedimint module."
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-dummy-tests"
publish = false
version = { workspace = true }

[[test]]
name = "fedimint_dummy_tests"
path = "tests/tests.rs"

[dependencies]
anyhow = { workspace = true }
fedimint-client = { workspace = true }
fedimint-client-module = { workspace = true }
fedimint-core = { workspace = true }
fedimint-dummy-client = { workspace = true }
fedimint-dummy-common = { workspace = true }
fedimint-dummy-server = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-server = { workspace = true }
fedimint-testing = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
