[package]
authors = { workspace = true }
description = "fedimint-recurringd-tests contains integration tests for fedimint-recurringd"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-recurringd-tests"
publish = false
version = { workspace = true }

[[bin]]
name = "fedimint-recurringd-tests"
path = "src/bin/fedimint-recurringd-tests.rs"

[dependencies]
anyhow = { workspace = true }
devimint = { workspace = true }
lightning-invoice = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
