[package]
authors = { workspace = true }
description = "Bitcoin RPC implementations for Fedimint server"
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-server-bitcoin-rpc"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
name = "fedimint_server_bitcoin_rpc"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
esplora-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-server-core = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
