[package]
authors = { workspace = true }
description = "A tiny command line tool to fetch BOLT11 invoices from LNURLs"
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = ["bitcoin", "lightning", "lnurl"]
license = { workspace = true }
name = "lnurlp"
readme = "README.md"
repository = { workspace = true }
version = { workspace = true }

[[bin]]
name = "lnurlp"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
fedimint-core = { workspace = true }
lightning-invoice = { workspace = true }
lnurl-rs = { workspace = true, features = ["async"] }
reqwest = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
