[package]
description = "fedimint-metrics allows exporting prometheus metrics from Fedimint."
edition = { workspace = true }
license = { workspace = true }
name = "fedimint-metrics"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_metrics"
path = "./src/lib.rs"

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
axum = { workspace = true }
fedimint-core = { workspace = true }
prometheus = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
