[package]
name = "fedimint-tbs"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "tbs is a helper cryptography library for threshold blind signatures"
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[features]
default = []
unstable = []

[lib]
name = "tbs"
path = "src/lib.rs"

[[bench]]
name = "tbs"
path = "benches/tbs.rs"
harness = false

[dependencies]
bls12_381 = { workspace = true }
fedimint-core = { workspace = true }
group = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
sha3 = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[lints]
workspace = true
