on: [push, pull_request]

name: Markdown Link Check

jobs:
  markdown-link-check:
    runs-on: [self-hosted, linux, x64]
    continue-on-error: true # can fail for external reasons, so don't be a blocker
    steps:
      - uses: actions/checkout@v4

      # Persist lychee cache, so we don't bother with checking same links all the time
      # Should also minimize number of flakes.
      - uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Check links
        run: nix run nixpkgs#lychee -- --verbose docs README.md
